### ISSUE TITLE
Signature: PackageIntegrityCheckFailed

### ISSUE THREAD

**Issue by joezhouchenye** [geezmolycos/vscode-hanzi-counter#1]
不能安装

![image](https://user-images.githubusercontent.com/59191277/225916570-a7ea2dca-6735-4b01-bc8c-d0cb6ae0ae17.png)

**Comment by geezmolycos** [comment]
有相关的日志吗，vs code的版本是多少？

**Comment by joezhouchenye** [comment]
![image](https://user-images.githubusercontent.com/59191277/225919241-90e83d9b-1786-4aa5-a7b4-9853e3bc2c20.png)

版本: 1.76.1
提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
日期: 2023-03-08T16:31:31.010Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.1.0-1004-oem
沙盒化: Yes

这个是之前的报错以及版本

已经通过VSIX安装上了

**Comment by geezmolycos** [comment]
刚才在 ubuntu 系统的 vs code 上复现成功该问题，用命令行安装旧版本，可以正常安装，唯独1.4.0无法安装。推测是上传到 marketplace 时出了问题。现已发布 1.4.1 版本，经测试已经可以正常安装。
