### ISSUE TITLE
点击高亮不可用，鼠标离开状态栏后弹出窗口会立即消失

### ISSUE THREAD

**Issue by dzx-dzx** [geezmolycos/vscode-hanzi-counter#2]
原先工作很正常。似乎在VSCode升级后(1.78.0)，鼠标悬停在状态栏上仍然能显示字数统计，但一离开状态栏字数统计就会消失，无法再点击高亮中文字。

我可能自己也改了什么配置，但我不太记得……

**Comment by geezmolycos** [comment]
已经拿 VS Code 1.78.0 测试了，确实有这个问题，我正在尝试解决

**Comment by geezmolycos** [comment]
修好了，发现是 VS Code 新版本改变了[弹出提示不消失的判断条件](https://github.com/microsoft/vscode/blob/d1aa00acef8b2cfa88621c448b8fd8cd034f60a9/src/vs/workbench/services/hover/browser/hoverWidget.ts#L205)。现在弹出提示里面必须要包括一个 Markdown 链接，才可以不消失。我的预设模板里面的链接用的是 html `<a>`，因此没被检测到。我添加了一个假的链接让它检测到。

现在已经发布了 1.5.2 版本修复问题，我测试已经修好了，你确认一下。

**Comment by dzx-dzx** [comment]
修好了，谢谢！

**Comment by dzx-dzx** [comment]
修好了，谢谢！
