### ISSUE TITLE
中西文混杂情况下的字数统计问题

### ISSUE THREAD

**Issue by wohenbushuang** [geezmolycos/vscode-hanzi-counter#3]
如：
> 使用 Adobe Photoshop 打开图片

```
Spaced words: | 4              [使用] [Adobe] [Photoshop] [打开图片]
Simple words: | 4               [使用] [Adobe] [Photoshop] [打开图片]
Sentences: | 1
Letters: | 20
Puncts/Symbols: | 0/0
Non-white: | 20
Chars: | 23
Non-ASCII: | 6
Codepoints: | 23
UTF-8: | 35


中文: | 6                         [使][用] Adobe Photoshop [打][开][图][片]
中文(不含标点): | 6        [使][用] Adobe Photoshop [打][开][图][片]
CJK字符: | 6
单词: | 4                         [使用] [Adobe] [Photoshop] [打开图片]
非空白字符: | 20
字符数: | 23
非ASCII码位: | 6
码位数: | 23
UTF-8: | 35
```

MS Word中的统计为：字数8，非中文单词2，中文字符和朝鲜语单词6，更符合日常使用习惯

同时还应考虑中西文间不打空格的情况（`使用Adobe Photoshop打开图片`）

**Comment by geezmolycos** [comment]
你的意思是这两点吗：
- 统计单词数的时候，完全不考虑类似中文的语言
- 统计中文字数时，也考虑英文单词，一个单词算成一个字

对于第一点现在的情况是，中文没有类似西文的 word，因此我在实现的时候挪用西文的习惯，将空格或标点分开的字（即一个短句）算成一个 word。我会考虑要不要在统计「单词数」时把类似中文的语言排除掉。
第二个问题是因为设计的时候「中文」就是只包括汉字字数的。

我感觉可以改一下「单词」这一项，改成算中文的时候一个一个字算。现在该项似乎不是很有用

**Comment by wohenbushuang** [comment]
> 我会考虑要不要在统计「单词数」时把类似中文的语言排除掉。

推荐，因为现在的显示是走分开语种统计的思路（不过目前在繁、日两个语种下统计的结果和简好像也是一样的）

我建议是，既能默认提供和word一样的统计，这样能和日常用途接轨；同时提供细分语种的统计，用于特殊需要和计算核查。目前情况是，无法基于现有的分语种统计数据加减得出和word一样的数据，还是要复制到word里去看一下。

**Comment by geezmolycos** [comment]
这个扩展的目标没有要和word一样，word统计字数的源码并不公开。如果一定要和word统计的结果一样，可以自己想办法写个符合的正则表达式添加进去。

我计划在统计西文页面单词数时，把类似中文的语言去掉；另外也会修改中文页面的「单词数」，把其他语言也考虑进来。繁日和简的汉字个数一样，是因为Unicode本身CJK字符都是统一表示的，强行区分还要考虑语境，比较难实现。

**Comment by wohenbushuang** [comment]
> 如果一定要和word统计的结果一样，可以自己想办法写个符合的正则表达式添加进去。

其实西文统计words时候别算上中文就好了，2+6=8

> 中文页面的「单词数」

这个名字感觉挺奇怪的，毕竟没有做分词，而且标点符号也会算在内，最后是一整行算1个单词……
中文的话，不如还是弄个行数或者段落数好了

**Comment by geezmolycos** [comment]
我发布了新的版本，禁用了一些不常用的项目，主要改了以下两点：
- 在所有「单词」的正则表达式规则中，排除了类似汉字的文字，因为汉字统计词数规则不同，和西文混合统计不合理
- 将中文页面的「单词数」换成「字词数」，并移动到首位，其计算方式为 CJK 字符（含标点）和西文单词数的和

你看看是否合适？

**Comment by wohenbushuang** [comment]
问题解决了，thx
